steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/splash-server-with-gcbuild/splash-server:${SHORT_SHA}', '.']
  images: 
- 'gcr.io/[PRODUCT_ID]/[CONTAINER_IMAGE]'
  timeout: 2000s
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/splash-server-with-gcbuild/splash-server']
  # deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'splash-server', '--image', 'gcr.io/splash-server-with-gcbuild/splash-server:${SHORT_SHA}', '--region', 'europe-west1', '--allow-unauthenticated']
  env:
  - 'PORT=8080'
  - 'HOST=0.0.0.0'
images:
- gcr.io/$PROJECT_ID/hello-cloud-run
